### PR TITLE
Supports logout endpoint (fixes #51)

### LINKED ISSUE #51: Support /logout endpoint
Once https://github.com/freedomofpress/securedrop/issues/3933 is implemented we will need to update the SDK to add support for the API logout endpoint.

### PR DESCRIPTION
**Pull request by kushaldas**
### How to test?

`make test` will use the mock data files.

You can run it against a development VM and execute the following command.

`make test TESTS=tests/test_api.py::TestAPI::test_logout`

### CODE REVIEW

**Comment by creviera** [comment]
I still need to run through these instructions to generate the test data https://github.com/freedomofpress/securedrop-sdk#generating-test-data-for-apiproxy, but also looks like a few tests are failing due to `AuthError`, checkout:

```
tests/test_api.py::TestAPI::test_reply_source
tests/test_api.py::TestAPI::test_reply_source_with_uuid
tests/test_api.py::TestAPI::test_star_add_remove
```

**Comment by kushaldas** [comment]
> checkout https://circleci.com/gh/freedomofpress/securedrop-sdk/341

The `test_logout` is logging the user and thus rest of the tests failing :man_facepalming:  Will fix this.

**Comment by kushaldas** [comment]
Easiest option is rename the test as `test_zlogout` @creviera what do you think about it?

**Comment by creviera** [comment]
So, is the problem that one of the tests logs the user out, making it so following tests that expect a logged-in user fail? Why does chaning the test name from `test_logout` to `test_zlogout` fix this?

**Comment by kushaldas** [comment]
> Why does chaning the test name from test_logout to test_zlogout fix this?

Then the logout is the last test to run :)

Otherwise we can modify the test code to sleep for 61 seconds and try again in case of logout.

**Comment by creviera** [comment]
Ah, I see why that would be the easiest thing to do. So the tests all share the same token then? Would having `test_logout` [get another token](https://docs.securedrop.org/en/release-0.13.0/development/journalist_api.html#authentication) after the test succeeds work?

**Pull request merged**
