### PR TITLE
add journalist name to session and reply obj

### PR DESCRIPTION
**Pull request by creviera**
# Description

In preparation for journalist badges in the conversation view (see https://github.com/freedomofpress/securedrop-client/issues/76), this PR adds `journalist_first_name` and `journalist_last_name` to the `Reply`, and makes a minor refactor so that the currently authenticated user details are:
`username`, `first_name`, and `last_name`

to differentiate from the reply sender details, which are called:
`journalist_username`, `journalist_first_name`, and `journalist_last_name`

### CODE REVIEW

**Comment by creviera** [comment]
Oops I auto-generated the test data for APIProxy on Debian instead of in Qubes which is why all these json an yml files look incorrect.

**Comment by creviera** [comment]
@kushaldas: I'm following the readme docs for generating sdk data files and still getting stuck. Here's what I did and where the failures occur:

> To test or to generate new test data file for the `APIProxy` class in
`test_apiproxy.py` file, you will have to setup
[QubesOS](https://qubes-os.org) system.
>

I already had Qubes installed so skipped.

> There should be one VM (let us call it `sd-journalist`), where we can run
latest securedrop server code from the development branch using
``NUM_SOURCES=5 make -C securedrop dev`` command. The same VM should also have
`securedrop-proxy` project installed, either from the source by hand or using
the latest Debian package from the FPF repository.
>

I downloaded the deb from https://apt.freedom.press/pool/main/s/securedrop-proxy/ and installed it using `dpkg -i securedrop-proxy_0.3.0+buster_all.deb` on my `sd-dev-buster` vm.

> Below is an example configuration for proxy `/etc/sd-proxy.yaml`:
>
>```
>host: 127.0.0.1
>scheme: http
>port: 8081
>target_vm: sd-svs
>dev: False
>```

I added this `.yaml` file to `sd-dev-buster` and copied it exactly except for replacing `sd-svs` with `sd-app`. 

Then I ran `NUM_SOURCES=5 make -C securedrop dev`.

>Then we can create our second developent VM called `sd-svs`, in which we can checkout/develop
>the `securedrop-sdk` project. The required configuration file is at `/etc/sd-sdk.conf`
>
>```
>[proxy]
>name=sd-journalist
>```
>

I added this `.conf` file to `sd-app` and copied it exactly except for replacing `sd-journalist` with `sd-dev-buster`. 

>We should also add a corresponding entry in `/etc/qubes-rpc/policy/securedrop.Proxy` file
in **dom0**.
>
>```
>sd-svs sd-journalist allow
>@anyvm @anyvm deny
>```
>

I added this `.Proxy` file to `dom0` which already had this entry: `sd-app sd-proxy allow` so I just added a new entry so that the contents of this file looked like:

```
sd-app sd-dev-buster allow
sd-app sd-proxy allow
@anyvm @anyvm deny
```

>The above mentioned setup can also be created using `securedrop-workstation` project.
>

I don't understand what this means.

>Now, delete any related JSON file under `data/` directory, or remove all of
them, and then execute ``make test TEST=tests/test_apiproxy.py``. This is
command will generate the new data files, which can be used in CI or any other
system.
>

I removed all of the data files via `rm -r data/*` in the `securedrop-sdk` repo on the `sd-app` VM.

Then I ran `make test TEST=tests/test_apiproxy.py` and saw all of the `tests/test_apiproxy.py::TestAPIProxy::test_*` tests fail.

>**Note:** Remember that file download checks don't read actual file path in the `APIProxy` tests as it requires QubesOS setup. You can manually uncomment those lines to execute them on QubesOS setup.

I don't know where this was mentioned before in the docs, so I don't recall this and don't understand.

**Comment by creviera** [comment]
> >Now, delete any related JSON file under `data/` directory, or remove all of
> them, and then execute ``make test TEST=tests/test_apiproxy.py``. This is
> command will generate the new data files, which can be used in CI or any other
> system.
> >
> 
> I removed all of the data files via `rm -r data/*` in the `securedrop-sdk` repo on the `sd-app` VM.
> 
> Then I ran `make test TEST=tests/test_apiproxy.py` and saw all of the `tests/test_apiproxy.py::TestAPIProxy::test_*` tests fail.

Based on feedback from Kushal, simply deleting the cassettes and rerun the test code is not enough to regenerate cassettes. There is a requirement to also comment out the decorator (here: https://github.com/freedomofpress/securedrop-sdk/blob/aa15037382494599ed1c07d5e32d03db9bd71f4d/tests/test_apiproxy.py#L29) in order to regenerate cassettes. Once I get this working I will definitely update the docs.

**Comment by creviera** [comment]
blocked on https://github.com/freedomofpress/securedrop-sdk/issues/128

**Comment by creviera** [comment]
This is ready now. Just going to rebase and sign...

**Review by kushaldas — APPROVED** [review]
This is okay, tests are good.

**Pull request merged**
