### PR TITLE
use latest pip-tools (see securedrop-debian-packaging#248)

### PR DESCRIPTION
**Pull request by creviera**
# Description

Rerun `make update-pip-requirements` with the latest pip-tools (see https://github.com/freedomofpress/securedrop-debian-packaging/pull/248) so that we can retag 0.3.0 and push a new sdk release to pypi. Also fix bug on `main` when you delete `.venv` and rerun `make venv`:

```
Collecting pip>=20.0 (from pip-tools==5.3.1->-r dev-requirements.txt (line 149))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    pip>=20.0 from https://files.pythonhosted.org/packages/7c/02/9ab8b431aca1b46fcc1ac830a5870a28a12ba1abfa681904b1d2da876a86/pip-21.2.1-py3-none-any.whl#sha256=da0ac9d9032d1d7bac69e9e301778f77b8b6626b85203f99edd2b545434d90a7 (from pip-tools==5.3.1->-r dev-requirements.txt (line 149))
make: *** [Makefile:7: venv] Error 1
```

### CODE REVIEW

**Comment by creviera** [comment]
# Test Plan

1. cd to your sdk project directory
2. `rm -r .venv`
3. `make venv`
- [ ] confirm no more `require-hashes mode` error around pinning pip-tools with `>=`
4. `source .venv/bin/activate` and run `make update-pip-requirements`
- [ ] confirm no errors now that you're using a more up-to-date version of `pip-compile`

**Comment by zenmonkeykstop** [comment]
Ran thru test plan, `make update-pip-requirements` completes successfully , but pip-tools version is 5.3.1, not latest.

**Comment by creviera** [comment]
> but pip-tools version is 5.3.1, not latest.

sry about that, pushed updated changes where it is pinned to 6.2.0 as expected

**Review by zenmonkeykstop — APPROVED** [review]
Test plan checks out, pip-tools at 6.2.0 (current latest)!

**Pull request merged**
