### PR TITLE
Adds APIProxy class to use securedrop-proxy

### LINKED ISSUE #16: Adapt SecureDrop SDK to SecureDrop Proxy Behavior
The SecureDrop Qubes OS proxy modifies requests with non-JSON responses (see https://github.com/freedomofpress/securedrop-proxy) - it uses `qvm-move` for those submissions. The SecureDrop SDK has to account for this behavior.

### PR DESCRIPTION
**Pull request by kushaldas**
The `APIProxy` class can now use `securedrop-proxy` service in the QubesOS. By default `sd-journalist` is the proxy name, but, we can override it using a configuration file at `/etc/sd-sdk.conf` file.

```
[proxy]
name = proxy-debian
```

## How to test?

```
pipenv run python -m unittest discover -v tests
```

We also found https://github.com/freedomofpress/securedrop-proxy/issues/11 while working on this.

Fixes #16.

### CODE REVIEW

**Comment by kushaldas** [comment]
Blah, now I should test it on my normal box.

**Comment by kushaldas** [comment]
Tests are failing because of the randomness of the dictionary.

**Comment by redshiftzero** [comment]
hey I started DRYing up the API and APIProxy classes in 218eaac729b4a3a7640508536367f9e72884b2fd, check it out and let me know what you think (still a few test failures to resolve, but an approach like this should trim down the added non-test code by 650 lines or so)

**Comment by kushaldas** [comment]
>hey I started DRYing up the API and APIProxy classes in 218eaac, check it out and let me know what you think (still a few test failures to resolve, but an approach like this should trim down the added non-test code by 650 lines or so)

This is a good start, I will look at the failing tests today.

**Comment by ntoll** [comment]
@redshiftzero nope... I'm not (knowingly) using etags, I'm consciously trying to do the simplest possible thing via this API layer. :-) I think you're safe to merge, and I'll certainly yelp if something breaks.

**Comment by redshiftzero** [comment]
ah great, thanks for confirming @ntoll ! mergin'

**Pull request merged**
