### PR TITLE
Use urljoin instead of string concat for urls

### PR DESCRIPTION
**Pull request by vivekanand1101**
Signed-off-by: Vivek Anand <vivekanand1101@gmail.com>

### CODE REVIEW

**Comment by vivekanand1101** [comment]
I haven't tested this manually, for that i will need to setup a few things.

**Comment by heartsucker** [comment]
Hey @vivekanand1101. There's been some commits to `master` since you opened this. Can you rebase on `master` and fix the conflicts?

**Comment by vivekanand1101** [comment]
@heartsucker it's been fixed. I didn't see your comments till now.

**Comment by kushaldas** [comment]
@vivekanand1101 Can you please resolve the conflict?

**Pull request merged**
