### PR TITLE
fix #30: changed incorrect error msg when downloading a file

### LINKED ISSUE #30: incorrect error message when downloading a file that 404s
When one downloads a submission with an invalid UUID, i.e. 

```
172.17.0.1 - - [25/Oct/2018 21:17:25] "GET /api/v1/sources/submissions/0d9cf7dd-a0f9-475c-bf97-aa5c31c5cd9b/download HTTP/1.1" 404 -
```

we get an incorrect message like:

```
'Missing reply 0d9cf7dd-a0f9-475c-bf97-aa5c31c5cd9b'
```

it should say missing submission

### PR DESCRIPTION
**Pull request by yatsenko-julia**
Fix #30

### CODE REVIEW

**Comment by 42B** [comment]
@yatsenko-julia 

Your commit message doesn't use the proper format to automatically close #30 . The problem seems to be the word "issue" that you are adding between "fix" and the issue number. 

Adding something like "Fix #30" in your PR description should handle it (or some combination from the link below)

* https://help.github.com/articles/closing-issues-using-keywords/

**Comment by kushaldas** [comment]
@yatsenko-julia Can you please squash those two commits into one? After that I can merge.

**Comment by yatsenko-julia** [comment]
@kushaldas As you requested I have squashed two commits into one.

**Comment by redshiftzero** [comment]
thanks @yatsenko-julia!

**Pull request merged**
